### ISSUE TITLE
Sending images to Claude (error)

### ISSUE THREAD

**Issue by Antoine2tt** [open-webui/pipelines#117] opened 2024-06-24 12:16 UTC
Hello ! 

It seems like https://github.com/open-webui/pipelines/pull/106 did the trick, claude 3.5 is working ! 👍 

But i've noticed something, if i try to send a .jpg file and ask a question about it, i have an error ;

![Capture d'écran 2024-06-24 141439](https://github.com/open-webui/pipelines/assets/979136/013dbdc6-f9c9-42fb-9cad-46140ce34335)

I've tried the same file with gpt 4o (in case of the problem was the file) but no errror ;

![Capture d'écran 2024-06-24 141513](https://github.com/open-webui/pipelines/assets/979136/57430c23-0004-4bb7-bb26-8d9bdfd7b93f)

Thanks for marking Claude working with open web ui, that's very cool ! 
Feel free to ask me anything if i can help 

Thanks !

**Comment by josephbkfung** [comment] 2024-06-24 19:05
This is duplicate of #114 and [justinh-rahb](https://github.com/justinh-rahb) will investigate how to make it works.

**Closed as completed** 2024-06-25 07:13 UTC

**Comment by justinh-rahb** [comment] 2024-06-26 12:55
Fixed:
- #124

**Comment by nickovs** [comment] 2024-06-26 21:27
I am still getting failures when trying to pass images in queries to Claude (but not during normal text chat).

<img width="670" alt="image" src="https://github.com/open-webui/pipelines/assets/4205868/e0c9ff53-50a7-4b93-b455-b57342daeb79">

The exception that is causing this failure seems to be:
```
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

The error does not depend on the image, prompt or model choice, only on if an image is present.

<details>
  <summary>Stack backtrace from logs:</summary>

```
open-webui  | INFO:     192.168.65.1:53960 - "POST /openai/chat/completions HTTP/1.1" 200 OK
pipelines   | INFO:     172.18.0.4:48414 - "POST /chat/completions HTTP/1.1" 200 OK
pipelines   | ERROR:    Exception in ASGI application
pipelines   | Traceback (most recent call last):
pipelines   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
pipelines   |     result = await app(  # type: ignore[func-returns-value]
pipelines   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
pipelines   |     return await self.app(scope, receive, send)
pipelines   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
open-webui  | ERROR:    Exception in ASGI application
pipelines   |     await super().__call__(scope, receive, send)
open-webui  | Traceback (most recent call last):
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 94, in connection_lost
pipelines   |     await self.middleware_stack(scope, receive, send)
open-webui  |     uncompleted = self._parser.feed_eof()
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
open-webui  |                   ^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |     raise exc
open-webui  |   File "aiohttp/_http_parser.pyx", line 507, in aiohttp._http_parser.HttpParser.feed_eof
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
open-webui  | aiohttp.http_exceptions.TransferEncodingError: 400, message:
pipelines   |     await self.app(scope, receive, _send)
open-webui  |   Not enough data for satisfy transfer length header.
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  | 
pipelines   |     with collapse_excgroups():
open-webui  | The above exception was the direct cause of the following exception:
pipelines   |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  | 
pipelines   |     self.gen.throw(typ, value, traceback)
open-webui  | Traceback (most recent call last):
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
pipelines   |     raise exc
open-webui  |     result = await app(  # type: ignore[func-returns-value]
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
open-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |     await func()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
open-webui  |     return await self.app(scope, receive, send)
pipelines   |     async for chunk in self.body_iterator:
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 65, in iterate_in_threadpool
open-webui  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
pipelines   |     yield await anyio.to_thread.run_sync(_next, as_iterator)
open-webui  |     await super().__call__(scope, receive, send)
pipelines   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
open-webui  |     await self.middleware_stack(scope, receive, send)
pipelines   |     return await get_async_backend().run_sync_in_worker_thread(
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
pipelines   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     raise exc
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
pipelines   |     return await future
open-webui  |     await self.app(scope, receive, _send)
pipelines   |            ^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
open-webui  |     with collapse_excgroups():
pipelines   |     result = context.run(func, *args)
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
pipelines   |              ^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     self.gen.throw(typ, value, traceback)
pipelines   |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 54, in _next
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
pipelines   |     return next(iterator)
open-webui  |     raise exc
pipelines   |            ^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
pipelines   |   File "/app/main.py", line 665, in stream_content
open-webui  |     await func()
pipelines   |     for line in res:
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
pipelines   |   File "/app/./pipelines/anthropic_manifold_pipeline.py", line 141, in stream_response
open-webui  |     return await super().stream_response(send)
pipelines   |     stream = self.client.messages.create(**payload)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pipelines   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anthropic/_utils/_utils.py", line 277, in wrapper
open-webui  |     async for chunk in self.body_iterator:
pipelines   |     return func(*args, **kwargs)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
pipelines   |            ^^^^^^^^^^^^^^^^^^^^^
open-webui  |     raise app_exc
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anthropic/resources/messages.py", line 904, in create
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
pipelines   |     return self._post(
open-webui  |     await self.app(scope, receive_or_disconnect, send_no_error)
pipelines   |            ^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anthropic/_base_client.py", line 1249, in post
open-webui  |     with collapse_excgroups():
pipelines   |     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
pipelines   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     self.gen.throw(typ, value, traceback)
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anthropic/_base_client.py", line 931, in request
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
pipelines   |     return self._request(
open-webui  |     raise exc
pipelines   |            ^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
pipelines   |   File "/usr/local/lib/python3.11/site-packages/anthropic/_base_client.py", line 1029, in _request
open-webui  |     await func()
pipelines   |     raise self._make_status_error_from_response(err.response) from None
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
pipelines   | anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
open-webui  |     return await super().stream_response(send)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
open-webui  |     async for chunk in self.body_iterator:
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
open-webui  |     raise app_exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
open-webui  |     await self.app(scope, receive_or_disconnect, send_no_error)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
open-webui  |     await self.simple_response(scope, receive, send, request_headers=headers)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
open-webui  |     await self.app(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     with collapse_excgroups():
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     self.gen.throw(typ, value, traceback)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
open-webui  |     await func()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
open-webui  |     return await super().stream_response(send)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
open-webui  |     async for chunk in self.body_iterator:
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
open-webui  |     raise app_exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
open-webui  |     await self.app(scope, receive_or_disconnect, send_no_error)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     with collapse_excgroups():
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     self.gen.throw(typ, value, traceback)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
open-webui  |     await func()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
open-webui  |     return await super().stream_response(send)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
open-webui  |     async for chunk in self.body_iterator:
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
open-webui  |     raise app_exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
open-webui  |     await self.app(scope, receive_or_disconnect, send_no_error)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
open-webui  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
open-webui  |     await app(scope, receive, sender)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
open-webui  |     await self.middleware_stack(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
open-webui  |     await route.handle(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 485, in handle
open-webui  |     await self.app(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
open-webui  |     await super().__call__(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
open-webui  |     await self.middleware_stack(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
open-webui  |     await self.app(scope, receive, _send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     with collapse_excgroups():
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     self.gen.throw(typ, value, traceback)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
open-webui  |     await func()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
open-webui  |     async for chunk in self.body_iterator:
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 50, in __anext__
open-webui  |     rv = await self.read_func()
open-webui  |          ^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 317, in readline
open-webui  |     return await self.readuntil()
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 351, in readuntil
open-webui  |     await self._wait("readuntil")
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 312, in _wait
open-webui  |     await waiter
open-webui  | aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

</details>
