### ISSUE TITLE
Unclear how to use pipelines

### ISSUE THREAD

**Issue by Fusseldieb** [open-webui/pipelines#55] opened 2024-06-04 14:20 UTC
I've tried to set up pipelines within my open-webui project, however it kinda lacks documentation on how to connect the pipelines to the OpenAI API, or similar.

_What do I mean by that?_

As per README:

> Set the API URL to http://localhost:9099 and the API key to 0p3n-w3bu!. Your pipelines should now be active.

This works. The connection establishes... But then _what_?

Since I removed the OpenAI URL and key to replace it with the localhost pipelines as per README, it no longer shows OpenAI models, which makes sense, however at this point the docs stop explaining what to do further, and I'm honestly a bit lost.
The example pipelines also don't show a OpenAI endpoint being called, so **where** do we put the OpenAI URL and keys, so it can pass through the pipeline into open-webui?

The Pipeline Admin panel is completely blank, too.

I'm somewhat puzzled. Any help is greatly appreciated.

**Comment by Fusseldieb** [comment] 2024-06-04 14:35
Turns out that the "Connection verified" message is flaky.
If you press save, you will get a "Connection verified" regardless if the pipelines API could be reached or not. 
Clicking on the refresh button yielded "OpenAI: Network Problem".

On further read, the README says:

> If your Open WebUI is running in a Docker container, replace localhost with host.docker.internal in the API URL.

So I put "http://host.docker.internal:9099", clicked refresh and it once again said "Connection verified", but this time it's actually connected. 

Opening up the Admin panel and going into Pipelins finally presents me with options! I found out that that's where the actual OpenAI API key must be placed.

**Comment by justinh-rahb** [comment] 2024-06-04 15:19
Pipelines server is an optional add-on for enhanced functionality not present in the WebUI proper. If you had working OpenAI models previously, just go back to what worked... Pipelines may not even be for you.

**Comment by Fusseldieb** [comment] 2024-06-04 15:22
Thanks for your answer @justinh-rahb . Yes, I know that. I'm not particularly new to Python so I found it neat.

I just discovered that I do need to add a pipeline provider, too, in order to use OpenAI.

Adding [this provider pipeline](https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/openai_manifold_pipeline.py) gave me an option to finally put the OpenAI API key. 

**It is now working.**

Still, I think the docs should mention that, even if it seems obvious for some haha

**Comment by justinh-rahb** [comment] 2024-06-04 15:34
> EDIT: Another thing worth mentioning is that the default (?) rate limiting pipeline _does not_ limit admins. I thought it wasn't working, so I set up a normal user account, and surely, it worked!

This was by design but we could probably make the user class(es) to filter selectable like in the conversation turn limiter filter.

**Comment by Fusseldieb** [comment] 2024-06-04 15:45
> > EDIT: Another thing worth mentioning is that the default (?) rate limiting pipeline _does not_ limit admins. I thought it wasn't working, so I set up a normal user account, and surely, it worked!
> 
> This was by design but we could probably make the user class(es) to filter selectable like in the conversation turn limiter filter.

That would be even neater, although it already works very well.

The only question that now arised is why I can't download two provider pipelines. I downloaded the OpenAI one, and it works as expected, but now that I try to download the [Anthropic one](https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/anthropic_manifold_pipeline.py), it just download it... and then _vanishes_. It doesn't appear in the pipelines. 

Is this intended?

**Comment by Fusseldieb** [comment] 2024-06-04 15:54
https://github.com/open-webui/pipelines/assets/4715129/3082e45a-aca9-40a7-9eaa-e7eca4449ccf

Something's going on, then...

**Comment by tjbck** [comment] 2024-06-04 17:04
If the code is in valid, the pipeline will be moved to `./pipelines/failed`. I'll investigate the issue with anthropic manifold.

**Comment by tjbck** [comment] 2024-06-04 17:06
Just pushed a fix, let me know if the issue persists.

**Closed by tjbck** 2024-06-04 17:06 UTC

**Comment by justinh-rahb** [comment] 2024-06-04 17:13
The issue is no anthropic key was set.

**Comment by Fusseldieb** [comment] 2024-06-04 17:14
> The issue is no anthropic key was set.

Nope, this isn't the issue. I was never prompted to set any key. It unloaded itself. I even pushed a patch branch with the defaults "your-api-key-here" to see if it still complains about the missing key, and it did.

Let's see if tjbck's fix solved it.

**Comment by Fusseldieb** [comment] 2024-06-04 17:19
> Just pushed a fix, let me know if the issue persists.

This fixed the issue. Thank you <3

**Comment by KhalfaniW** [comment] 2024-07-12 06:09
I'm on linux and kept getting `OpenAI: Network Problem`

 http://localhost:9099 and http://host.docker.internal:9099  did not work for me

 I tried http://172.17.0.1:9099/ and it worked

**Comment by har-singh** [comment] 2025-02-07 13:46
> I'm on linux and kept getting `OpenAI: Network Problem`
> 
> http://localhost:9099 and http://host.docker.internal:9099 did not work for me
> 
> I tried http://172.17.0.1:9099/ and it worked

I was getting the same error even with `http://172.17.0.1:9099`. As soon as I used **`http://10.182.0.5:9099`** the connections was successful.

```bash
user@ubuntu:~$ ip address | grep 'inet '
    inet 127.0.0.1/8 scope host lo
    inet 10.182.0.5/24 metric 100 brd 10.182.0.255 scope global eth0
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
```

Note: also noticed that `http://10.182.0.5:9099/` (**with trailing slash**) does not work.
