### ISSUE TITLE
feat: azure openai endpoint support

### ISSUE THREAD

**Issue by gregrobison** [open-webui/pipelines#36] opened 2024-01-09 17:39 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to get my Azure OpenAI API endpoint to be recognized - are there any additional settings needed?

**Describe the solution you'd like**
Azure OpenAI endpoint cannot connect.

**Describe alternatives you've considered**
API works in other environments. 

**Additional context**

**Comment by tjbck** [comment] 2024-06-02 06:00
Implemented as Pipeline: https://github.com/open-webui/pipelines/blob/main/examples/providers/azure_openai_pipeline.py

**Comment by kentsuiGitHub** [comment] 2024-06-03 10:20
Thanks 
Tried the pipeline and failed to run
Endpoint url is incorrect which with extra “chat”

**Comment by kentsuiGitHub** [comment] 2024-06-04 08:52
tried the pipeline and find hit error 500. Further checked the request body JSON is not match with Azure OpenAI ChatCompletion API schema.

**Comment by TDaubignyElsan** [comment] 2024-06-06 10:19
> tried the pipeline and find hit error 500. Further checked the request body JSON is not match with Azure OpenAI ChatCompletion API schema.

Same here, is there a way to fix it ?

**Comment by tjbck** [comment] 2024-06-06 11:12
@TDaubignyElsan @kentsuiGitHub I don't use Azure myself (I don't have the keys to test it) so PR welcome!

**Comment by TDaubignyElsan** [comment] 2024-06-06 15:06
> @TDaubignyElsan @kentsuiGitHub I don't use Azure myself (I don't have the keys to test it) so PR welcome!

Related documentation is located just here : https://learn.microsoft.com/en-us/azure/ai-services/openai/reference if it can help ?

**Comment by justinh-rahb** [comment] 2024-06-06 15:53
> Related documentation is located just here : https://learn.microsoft.com/en-us/azure/ai-services/openai/reference if it can help ?

The issue isn't with finding documentation, it's the inability for the team to _test_ it since we do not have access. We could be open to someone offering us a limited scope key via Discord PM to move this forward.

**Comment by Gyarbij** [comment] 2024-06-14 06:55
> > Related documentation is located just here : https://learn.microsoft.com/en-us/azure/ai-services/openai/reference if it can help ?
> 
> The issue isn't with finding documentation, it's the inability for the team to _test_ it since we do not have access. We could be open to someone offering us a limited scope key via Discord PM to move this forward.
> 

I can help with that, if someone wants to shoot me dm. on discord you can also find me under Gyarbij.

**Comment by justinh-rahb** [comment] 2024-08-02 14:17
Closing as we've had a pipeline for this for a while now.

**Closed by justinh-rahb** 2024-08-02 14:17 UTC
Labels: enhancement, good first issue
